image:
  repository: robotshopdevacr.azurecr.io/baseimages/fluent/fluent-bit
  tag: 4.1.0-internal
  pullPolicy: Always

env:
  - name: ES_USER
    valueFrom:
      secretKeyRef:
        name: elasticsearch
        key: ES_USER

  - name: ES_PASS
    valueFrom:
      secretKeyRef:
        name: elasticsearch
        key: ES_PASS

config:
  service: |
    [SERVICE]
        Flush         1
        Daemon        Off
        Log_Level     info
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

  inputs: |
    [INPUT]
        Name       tail
        Path       /var/log/containers/*.log
        Parser     cri
        Tag        kube.var.log.containers.*

  filters: |
    [FILTER]
        Name       kubernetes
        Match      kube.var.log.containers.*
        Merge_Log  On
        Keep_Log   Off

    [FILTER]
        Name          parser
        Match         kube.var.log.containers.*
        Key_Name      message
        Parser        json
        Reserve_Data  On
        Preserve_Key  On

  outputs: |
    [OUTPUT]
        Name                es
        Match               *
        Host                10.0.2.10
        Port                9200
        HTTP_User           ${ES_USER}
        HTTP_Passwd         ${ES_PASS}
        tls                 on
        tls.verify          off
        Suppress_Type_Name  On 
        Index               robotshop
        Logstash_Format     On
        Logstash_Prefix     robotshop

  customParsers: |
    [PARSER]
      Name    json
      Format  json