name: Validate and Deploy Fluentbit helm charts to Development

on:
  push:
    branches-ignore:
      - "main"
  
  pull_request:
    branches:
      - develop    

  workflow_dispatch:

jobs:
  deploy:
    uses: robot-shop-DevOps/robot-shop-github-actions/.github/workflows/helm-charts.yaml@main
    with:
      RELEASE_NAME: fluentbit
      NAMESPACE: fluentbit
      CHART_REPO_NAME: fluent
      CHART_REPO_URL: https://fluent.github.io/helm-charts
      CHART_NAME: fluent-bit
      CHART_VERSION: 0.54.0
      CHART_PATH: ./.chart
      VALUES_FILES: ".chart/values.yaml .chart/values/values_dev.yaml"
    secrets: inherit